services:
  - type: web
    name: usl-clinical-screening
    runtime: python # Specify python runtime
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app_updated.py --server.port $PORT --server.headless true --server.runOnSave false --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 # Explicitly set the Python version
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    autoDeploy: false
    # The health check path for a Streamlit app is /_stcore/health
    healthCheckPath: /_stcore/health
    # Using free tier with aggressive memory optimizations
    # Note: Free instances do not support persistent disks.
